"""add_photo_url_to_users

Revision ID: 041c289ca3fc
Revises: 85812b29f47f
Create Date: 2025-11-25 18:13:07.579282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041c289ca3fc'
down_revision: Union[str, None] = '85812b29f47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('whatsapp_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_number')
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
