"""Add superset_id to workout_items

Revision ID: 082f2866d8a4
Revises: 14921db2c8a1
Create Date: 2025-11-26 18:06:03.335462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082f2866d8a4'
down_revision: Union[str, None] = '14921db2c8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_items', sa.Column('superset_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_items', 'superset_id')
    # ### end Alembic commands ###
