"""add_intelligence_upgrade_fields

Revision ID: 134c35b357a7
Revises: bd6c7f93d089
Create Date: 2025-11-23 22:22:21.356677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '134c35b357a7'
down_revision: Union[str, None] = 'bd6c7f93d089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types first
    musclegroup_enum = sa.Enum('CHEST', 'BACK', 'LEGS', 'ARMS', 'SHOULDERS', 'CORE', 'CARDIO', name='musclegroup')
    musclegroup_enum.create(op.get_bind(), checkfirst=True)
    
    gender_enum = sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender')
    gender_enum.create(op.get_bind(), checkfirst=True)
    
    # Now add columns
    op.add_column('exercise_library', sa.Column('muscle_group', musclegroup_enum, nullable=True))
    op.add_column('exercise_library', sa.Column('met_value', sa.Float(), nullable=True))
    op.add_column('exercise_library', sa.Column('video_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_exercise_library_muscle_group'), 'exercise_library', ['muscle_group'], unique=False)
    op.add_column('users', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('users', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('workout_sessions', sa.Column('calories_burned', sa.Integer(), nullable=True))
    op.alter_column('workout_sessions', 'progress_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'progress_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('workout_sessions', 'calories_burned')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'gender')
    op.drop_index(op.f('ix_exercise_library_muscle_group'), table_name='exercise_library')
    op.drop_column('exercise_library', 'video_url')
    op.drop_column('exercise_library', 'met_value')
    op.drop_column('exercise_library', 'muscle_group')
    
    # Drop ENUM types
    sa.Enum(name='gender').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='musclegroup').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
