"""Add duration_seconds to workout_items

Revision ID: 14921db2c8a1
Revises: f819142bef4d
Create Date: 2025-11-26 12:46:02.246973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14921db2c8a1'
down_revision: Union[str, None] = 'f819142bef4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_invites', 'trainer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('workout_items', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_items', 'duration_seconds')
    op.alter_column('student_invites', 'trainer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
