"""Add whatsapp_number to trainer_profile

Revision ID: 2e4095e1983a
Revises: 1bcb3a20042b
Create Date: 2025-11-22 21:34:16.211515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4095e1983a'
down_revision: Union[str, None] = '1bcb3a20042b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_profiles', sa.Column('whatsapp_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_profiles', 'whatsapp_number')
    # ### end Alembic commands ###
