"""Initial migration

Revision ID: 5588bc73114d
Revises: 
Create Date: 2025-11-22 13:21:54.128182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5588bc73114d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_iot_compatible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_library_category'), 'exercise_library', ['category'], unique=False)
    op.create_index(op.f('ix_exercise_library_name'), 'exercise_library', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('TRAINER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('body_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('photo_front_url', sa.String(), nullable=True),
    sa.Column('photo_side_url', sa.String(), nullable=True),
    sa.Column('photo_back_url', sa.String(), nullable=True),
    sa.Column('body_fat_percent', sa.Float(), nullable=True),
    sa.Column('muscle_mass_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='assessmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=False),
    sa.Column('reps_max', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('target_zone_min_bpm', sa.Integer(), nullable=True),
    sa.Column('target_zone_max_bpm', sa.Integer(), nullable=True),
    sa.Column('target_rpe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_items')
    op.drop_table('body_assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercise_library_name'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_category'), table_name='exercise_library')
    op.drop_table('exercise_library')
    # ### end Alembic commands ###
