"""add_multi_tenant_models

Revision ID: 6af9f7d33ed2
Revises: a1f2c78a5634
Create Date: 2025-11-22 15:42:07.439818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6af9f7d33ed2'
down_revision: Union[str, None] = 'a1f2c78a5634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums
    # Note: userrole already exists, we need to add SUPER_ADMIN
    # We use execute because alembic doesn't auto-migrate enum values easily
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'SUPER_ADMIN'")
    
    subscription_status = sa.Enum('ACTIVE', 'INACTIVE', 'TRIAL', name='subscriptionstatus')
    subscription_status.create(op.get_bind(), checkfirst=True)

    # workout_session_status is created by create_table below automatically

    op.create_table('trainer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('enable_iot', sa.Boolean(), nullable=True),
    sa.Column('enable_ai_vision', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'FINISHED', 'ABANDONED', name='workoutsessionstatus'), nullable=True),
    sa.Column('shareable_image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.Enum('ACTIVE', 'INACTIVE', 'TRIAL', name='subscriptionstatus'), nullable=True))
    op.add_column('users', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('xp_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('medical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workout_items', sa.Column('weight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_items', 'weight_kg')
    op.drop_column('users', 'medical_history')
    op.drop_column('users', 'level')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'xp_points')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'is_active')
    op.drop_table('workout_sessions')
    op.drop_table('trainer_profiles')
    # ### end Alembic commands ###
