"""add_anamnesis_and_invites

Revision ID: 85812b29f47f
Revises: f67555b979de
Create Date: 2025-11-25 10:47:53.514731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85812b29f47f'
down_revision: Union[str, None] = 'f67555b979de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', name='invitestatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_invites_email'), 'student_invites', ['email'], unique=True)
    op.create_index(op.f('ix_student_invites_id'), 'student_invites', ['id'], unique=False)
    op.create_index(op.f('ix_student_invites_token'), 'student_invites', ['token'], unique=True)
    op.add_column('users', sa.Column('anamnesis_completed', sa.Boolean(), nullable=True))
    op.alter_column('workout_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'anamnesis_completed')
    op.drop_index(op.f('ix_student_invites_token'), table_name='student_invites')
    op.drop_index(op.f('ix_student_invites_id'), table_name='student_invites')
    op.drop_index(op.f('ix_student_invites_email'), table_name='student_invites')
    op.drop_table('student_invites')
    # ### end Alembic commands ###
