"""add_heart_rate_data_to_workout_session

Revision ID: 8966424b3136
Revises: 0107a17a6621
Create Date: 2025-11-26 22:50:01.619378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8966424b3136'
down_revision: Union[str, None] = '0107a17a6621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('heart_rate_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'heart_rate_data')
    # ### end Alembic commands ###
