"""Add Workout model and update items

Revision ID: a1f2c78a5634
Revises: 5588bc73114d
Create Date: 2025-11-22 13:27:52.486299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f2c78a5634'
down_revision: Union[str, None] = '5588bc73114d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workout_items', sa.Column('workout_id', sa.UUID(), nullable=False))
    op.add_column('workout_items', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('workout_items', 'reps_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_items', 'reps_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_items', 'target_rpe',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('workout_items_user_id_fkey'), 'workout_items', type_='foreignkey')
    op.create_foreign_key(None, 'workout_items', 'workouts', ['workout_id'], ['id'])
    op.drop_column('workout_items', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_items', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_items', type_='foreignkey')
    op.create_foreign_key(op.f('workout_items_user_id_fkey'), 'workout_items', 'users', ['user_id'], ['id'])
    op.alter_column('workout_items', 'target_rpe',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_items', 'reps_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_items', 'reps_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('workout_items', 'notes')
    op.drop_column('workout_items', 'workout_id')
    op.drop_table('workouts')
    # ### end Alembic commands ###
