"""make_hiring_request_student_id_nullable

Revision ID: d323e3c50e4a
Revises: 7044c269002a
Create Date: 2026-04-04 18:40:24.349545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd323e3c50e4a'
down_revision: Union[str, None] = '7044c269002a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hiring_requests', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hiring_requests', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
