"""make_trainer_id_nullable_in_invites

Revision ID: f819142bef4d
Revises: 041c289ca3fc
Create Date: 2025-11-25 19:40:23.909573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f819142bef4d'
down_revision: Union[str, None] = '041c289ca3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_invites', 'trainer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_invites', 'trainer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
