"""add_modality_and_gyms_to_trainer_profile

Revision ID: q1r2s3t4u5v6
Revises: d323e3c50e4a
Create Date: 2026-04-05 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'q1r2s3t4u5v6'
down_revision: Union[str, None] = 'd323e3c50e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_profiles', sa.Column('modality', sa.String(), nullable=True))
    op.add_column('trainer_profiles', sa.Column('gyms', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_profiles', 'gyms')
    op.drop_column('trainer_profiles', 'modality')
    # ### end Alembic commands ###
