from fastapi import APIRouter
from app.api.endpoints import workouts, auth, users, exercises, assessments, admin, gamification, trainer, student, plans, uploads, recovery, workout_groups, invites, admin_import, marketplace, workout_session, websockets, public, ai_workouts, workout_templates, reviews, notifications, files, exercise_groups, telemetry, ai_agent, chat

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["login"])
api_router.include_router(telemetry.router, prefix="/telemetry", tags=["telemetry"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(exercises.router, prefix="/exercises", tags=["exercises"])
api_router.include_router(workouts.router, prefix="/workouts", tags=["workouts"])
api_router.include_router(workout_groups.router, prefix="/workout-groups", tags=["workout-groups"])
api_router.include_router(assessments.router, prefix="/assessments", tags=["assessments"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(gamification.router, prefix="/gamification", tags=["gamification"])
api_router.include_router(trainer.router, prefix="/trainer", tags=["trainer"])
api_router.include_router(student.router, prefix="/student", tags=["student"])
api_router.include_router(plans.router, prefix="/admin/plans", tags=["plans"])
api_router.include_router(uploads.router, prefix="/uploads", tags=["uploads"])
api_router.include_router(invites.router, prefix="/invites", tags=["invites"])
api_router.include_router(admin_import.router, prefix="/admin", tags=["admin-import"])
api_router.include_router(marketplace.router, prefix="/marketplace", tags=["marketplace"])
api_router.include_router(workout_session.router, prefix="/workout-sessions", tags=["workout-sessions"])
api_router.include_router(websockets.router, prefix="/ws", tags=["websockets"])
api_router.include_router(public.router, prefix="/public", tags=["public"])
api_router.include_router(ai_workouts.router, prefix="/ai-workouts", tags=["ai-workouts"])
api_router.include_router(ai_agent.router, prefix="/ai-agent", tags=["ai-agent"])
api_router.include_router(workout_templates.router, prefix="/workout-templates", tags=["workout-templates"])
api_router.include_router(reviews.router, prefix="/reviews", tags=["reviews"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(files.router, prefix="/files", tags=["files"])
api_router.include_router(exercise_groups.router, prefix="/exercise-groups", tags=["exercise-groups"])
api_router.include_router(chat.router, prefix="/chat", tags=["chat"])

